joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

camera_position_controller:
  type: effort_controllers/JointPositionController
  joint: camera_joint
  pid: { p: 0.1, i: 0.0, d: 3.0 }
